# """
#  Config file to setup scene environment in moveit. 
#  Please subscribe to planning scene in rviz to see what is happening. 
#  * The object must be called object_1, object_2 and so on. 
#  * type: 1 for box, 2 sphere, 3 clinder, 4 cone. 
# """

objects:
  object_1: {type: 1, dimensions: [2,0.1,2],   pose: [0,1.2,0.5,0,0,0,1]}  # side wall
  object_2: {type: 1, dimensions: [0.13,0.13,1], pose: [0,0,-0.5,0,0,0,1]} # support
  object_3: {type: 1, dimensions: [2,2,0.1], pose: [0,0,1.4,0,0,0,1]}        # ceiling   
