# Storing all markers type, and extended tf-tree
# Check YAML: http://www.yamllint.com/

marker_id:
  marker_0: {type: "tray_marker" }
  marker_1: {type: "tray_marker" }
  marker_2: {type: "tray_marker" }
  marker_3: {type: "tray_marker" }
  marker_100: {type: "compartment_marker" }
  marker_101: {type: "compartment_marker" }
  marker_102: {type: "compartment_marker" }
  marker_103: {type: "compartment_marker" }

marker_extended_frames:
  tray_marker:        [pre-pick, insert, lift, post-pick]
  compartment_marker: [pre-place, insert, drop, post-place]

markers_extended_tf:
  tray_marker:
    pre-pick:   [0,   0.004,   0.33,   1.57,   -1.57,    0]
    insert:     [0,   0.004,   0.02,     1.57,   -1.57,    0]
    lift:       [0,   -0.05,   0.02,     1.57,   -1.57,    0]
    post-pick:  [0,   -0.02,   0.33,   1.57,   -1.57,    0]
  compartment_marker:     
    pre-place:  [0,   -0.1,   0.33,   1.57,   -1.57,    0]
    insert:     [0,   -0.1,   0,     1.57,   -1.57,    0]
    drop:       [0,   -0.05,  0,     1.57,   -1.57,    0]
    post-place: [0,   -0.05,  0.33,   1.57,   -1.57,    0]

# TODO
eef_to_tool_offset: 0.043
