controller_list:
  - name: ""
    ## when running: 'ur_modern_driver'
    # action_ns: follow_joint_trajectory 
    ## when running: 'ur_robot_driver'
    action_ns: scaled_pos_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
